//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discord_rAthenaBot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discord Bot - rAthena - 2016")]
        public string ConsoleTitle {
            get {
                return ((string)(this["ConsoleTitle"]));
            }
            set {
                this["ConsoleTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rAthena")]
        public string ServerName {
            get {
                return ((string)(this["ServerName"]));
            }
            set {
                this["ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("general")]
        public string ChannelGeneral {
            get {
                return ((string)(this["ChannelGeneral"]));
            }
            set {
                this["ChannelGeneral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rules")]
        public string ChannelRules {
            get {
                return ((string)(this["ChannelRules"]));
            }
            set {
                this["ChannelRules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/")]
        public char PrefixChar {
            get {
                return ((char)(this["PrefixChar"]));
            }
            set {
                this["PrefixChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowMentionPrefix {
            get {
                return ((bool)(this["AllowMentionPrefix"]));
            }
            set {
                this["AllowMentionPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>https://rathena.org/board/forum/211-general-support.xml/</string>
  <string>https://rathena.org/board/forum/24-installation-support.xml/</string>
  <string>https://rathena.org/board/forum/30-scripting-support.xml/</string>
  <string>https://rathena.org/board/forum/31-database-support.xml/</string>
  <string>https://rathena.org/board/forum/35-source-support.xml/</string>
  <string>https://rathena.org/board/forum/40-graphics-support.xml/</string>
  <string>https://rathena.org/board/forum/21-web-support.xml/</string>
  <string>https://rathena.org/board/forum/19-client-side-support.xml/</string>
  <string>https://rathena.org/board/forum/214-third-party-support.xml/</string>
  <string>https://rathena.org/board/forum/22-linux-support.xml/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RSSList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RSSList"]));
            }
            set {
                this["RSSList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800000")]
        public long RSSInterval {
            get {
                return ((long)(this["RSSInterval"]));
            }
            set {
                this["RSSInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RSSAutoReset {
            get {
                return ((bool)(this["RSSAutoReset"]));
            }
            set {
                this["RSSAutoReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RSSEnabled {
            get {
                return ((bool)(this["RSSEnabled"]));
            }
            set {
                this["RSSEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("support")]
        public string ChannelSupport {
            get {
                return ((string)(this["ChannelSupport"]));
            }
            set {
                this["ChannelSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YOUR_CUSTOM_BOT_TOKEN")]
        public string Token {
            get {
                return ((string)(this["Token"]));
            }
            set {
                this["Token"] = value;
            }
        }
    }
}
